version: '3.8'

services:
  leaderz-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # Add your environment variables here or use a .env file
      # - TWILIO_ACCOUNT_SID=your_twilio_account_sid
      # - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      # - TWILIO_PHONE_NUMBER=whatsapp:+14155238886
      # - APP_BASE_URL=http://localhost:3000
      # - LEADERBOARD_BASE_URL=http://localhost:3000/leaderboardz
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 